### ISSUE TITLE
gauge initialization

### ISSUE THREAD

**Issue by vliedel** [geekammo/MicroView-Arduino-Library#25]
I was trying out the gauge, with the following code:
```
#include <MicroView.h>

MicroViewGauge gauge(23, 23, -20, 20, WIDGETSTYLE3);

void setup() {
  uView.begin();
  uView.clear(PAGE);
}


void loop() {
  gauge.setValue(19);
  uView.display();
  delay(1000);

  gauge.setValue(10);
  uView.display();
  delay(1000);
}
```

But then the gauge face is missing and a pointer at the minimum value was drawn. I had to add <code>gauge.reDraw();</code> in the setup() to fix this.

**Comment by vliedel** [comment]
Ah, probably because uView.begin() and uView.clear() are called after creating the widget.

**Comment by jpliew** [comment]
Yes, the widget is being drawn at the init, then clear(PAGE) cleared the widget, therefore you have no widget. calling reDraw() will redraw the widget face.
