### ISSUE TITLE
hide widgets

### ISSUE THREAD

**Issue by vliedel** [geekammo/MicroView-Arduino-Library#26]
Hi, it would be a nice feature to be able to hide widgets, so that they don't get displayed.
This way you can easily switch between 2 different screens, without storing all the values yourself.

**Comment by jpliew** [comment]
Hi,

You should be able to do it with clear (PAGE) then draw another widget, then clear (PAGE) then call redraw on the first widget.

Cheers
JP

**Comment by MLXXXp** [comment]
@jpliew, I was going to suggest the same thing.
However, @vliedel I think what you're trying to point out is that when you use **setValue()** to change the widget value, it also draws the new value to the screen buffer. This means you can't change the value of widgets that you want "hidden" (meaning they're not on the current display). You would have to create and update copies of the values of hidden widgets and then use them with **setValue()** only when you "unhide" them.

I've made changes to the widget **setValue()** function in the library. I overloaded it to add a new optional second argument **doDraw**. If you include this argument and set it to *false*, the value is set but the display buffer isn't updated. If set to *true*, or you don't include the second argument, it works as before and the display buffer is updated with the new value.

These changes are in the *widget_setvalue_nodraw* branch of my fork of the library. You can get the changed library for testing from here:
https://github.com/MLXXXp/MicroView-Arduino-Library/tree/widget_setvalue_nodraw

If these changes work, and solve the problem adequately, and there are no objections, I can create a pull request to have them added here in the official geekammo library.

**Comment by vliedel** [comment]
Yeah that would be a nice way indeed :)

**Comment by MLXXXp** [comment]
I've created pull request #27 to include these changes.

I've also created a pull request, #28, which adds sketch **MicroViewWidgetBackground** to the examples, to demonstrate the new feature.
