### ISSUE TITLE
Compilation gives an error after adding the WaveHc.h library

### ISSUE THREAD

**Issue by ghost** [geekammo/MicroView-Arduino-Library#30]
// This my code : 

<pre>
const char PROGMEM
  boot[] = "boot", annc[] = "annc", am[] = "am", pm[] = "pm",
  h01[] = "h01", h02[] = "h02", h03[] = "h03", h04[] = "h04",
  h05[] = "h05", h06[] = "h06", h07[] = "h07", h08[] = "h08",
  h09[] = "h09", h10[] = "h10", h11[] = "h11", h12[] = "h12",
  m00[] = "m00", m10[] = "m10", m20[] = "m20",
  m30[] = "m30", m40[] = "m40", m50[] = "m50",
  m11[] = "m11", m12[] = "m12", m13[] = "m13",
  m14[] = "m14", m15[] = "m15", m16[] = "m16",
  m17[] = "m17", m18[] = "m18", m19[] = "m19",
  m0x[] = "m0x", m2x[] = "m2x", m3x[] = "m3x", m4x[] = "m4x", m5x[] = "m5x",
  m1[] = "m1", m2[] = "m2", m3[] = "m3",
  m4[] = "m4", m5[] = "m5", m6[] = "m6",
  m7[] = "m7", m8[] = "m8", m9[] = "m9",
  *hours[]  = { h12, h01, h02, h03, h04, h05, h06, h07, h08, h09, h10, h11 },
  *mTens[]  = { m00, m10, m20, m30, m40, m50 },
  *mTeens[] = { m11, m12, m13, m14, m15, m16, m17, m18, m19 },
  *mTenX[]  = { m0x, NULL, m2x, m3x, m4x, m5x },
  *mins[]   = { m1, m2, m3, m4, m5, m6, m7, m8, m9 },
  *ampm[]   = { am, pm };
</pre>

---

// and this error messages : 

<pre>
Arduino:1.6.6 (Windows 10), Kart:"Arduino/Genuino Uno"

TalkingClock:64: error: variable 'hours' must be const in order to be put into read-only section by means of '__attribute__((progmem))'

   *hours[]  = { h12, h01, h02, h03, h04, h05, h06, h07, h08, h09, h10, h11 },

          ^

TalkingClock:65: error: variable 'mTens' must be const in order to be put into read-only section by means of '__attribute__((progmem))'

   *mTens[]  = { m00, m10, m20, m30, m40, m50 },

          ^

TalkingClock:66: error: variable 'mTeens' must be const in order to be put into read-only section by means of '__attribute__((progmem))'

   *mTeens[] = { m11, m12, m13, m14, m15, m16, m17, m18, m19 },

           ^

TalkingClock:67: error: variable 'mTenX' must be const in order to be put into read-only section by means of '__attribute__((progmem))'

   *mTenX[]  = { m0x, NULL, m2x, m3x, m4x, m5x },

          ^

TalkingClock:68: error: variable 'mins' must be const in order to be put into read-only section by means of '__attribute__((progmem))'

   *mins[]   = { m1, m2, m3, m4, m5, m6, m7, m8, m9 },

         ^

TalkingClock:69: error: variable 'ampm' must be const in order to be put into read-only section by means of '__attribute__((progmem))'

   *ampm[]   = { am, pm };

         ^

D:\yedekler\belgelerim\Arduino\TalkingClock\TalkingClock.ino: In function 'void setup()':

TalkingClock:75: error: 'mcpDacInit' was not declared in this scope

   mcpDacInit();               // Audio DAC is

              ^

TalkingClock:77: error: 'mcpDacSend' was not declared in this scope

     mcpDacSend(i);            // to avoid startup 'pop'

                 ^

exit status 1
variable 'hours' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
</pre>

**Comment by MLXXXp** [comment]
This doesn't appear to have anything to do with the MicroView library.

I don't think it has anything to do with the WaveHc library either.

Perhaps this can be of some help:
https://github.com/arduino/Arduino/wiki/1.6-Frequently-Asked-Questions#q-i-have-a-similar-error-but-it-seems-to-be-already-const-heres-the-error-variable-lotofmessages-must-be-const-in-order-to-be-put-into-read-only-section-by-means-of-__attribute__progmem-const-char-lotofmessages-progmem--

**Comment by czetie** [comment]
Yep, I think this is a generic C programming error. The problem seems to be
that 'hours' is a pointer to a constant, but is not itself a constant. You
need to declare a constant pointer to a constant, something like this:

const char PROGMEM const *hours[] = ....

--CZ

On Wed, Nov 18, 2015 at 9:17 AM, Scott Allen notifications@github.com
wrote:

> This doesn't appear to have anything to do with the MicroView library. I
> get the same errors even if I don't include MicroView.h
> 
> I don't think it has anything to do with the WaveHc library either.
> 
> Perhaps this can be of some help:
> 
> https://github.com/arduino/Arduino/wiki/1.6-Frequently-Asked-Questions#q-i-have-a-similar-error-but-it-seems-to-be-already-const-heres-the-error-variable-lotofmessages-must-be-const-in-order-to-be-put-into-read-only-section-by-means-of-__attribute__progmem-const-char-lotofmessages-progmem--
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geekammo/MicroView-Arduino-Library/issues/30#issuecomment-157725743
> .

## 

The contents of this message represent the
personal opinion of Carl Zetie and do not
reflect the opinions of his employer
